### ISSUE TITLE
installing for python3

### ISSUE THREAD

**Issue by jnishiji** [masroore/pg_simple#5]
i run the command 'pip3 install pg_simple' and it fails because of an import error: 'ImportError: cannot import name 'config_pool' from 'pool''. 
Am I doing something wrong?

**Comment by MattC8915** [comment]
I'm also having this issue

**Comment by victornoleto** [comment]
Same here

**Comment by juregvoz** [comment]
The fixes for python3 compatibilty were added in 2018 to this repo. However, the last release **0.2.3** on PyPi was made in [2014 ](https://pypi.org/project/pg_simple/) and when you run **"pip install pg_simple"** this is the version that you are trying to install.
 You can install the latest changes by cloning the repo, navigating with console to the folder that include **setup.py** file and running
**"pip install ."** . And make sure that you first install **psycopg2**. I'm using **psycopg2** version **2.7.6.1** and they work fine together, but I don't know if newer versions are also compatible with **pg-simple 0.2.3**.

**Comment by masroore** [comment]
Release 0.2.4 has been pushed to PyPi with py3k compatibilty. I hope this release resolves the compatibility issues. Regards.
